version: '3'
services:
  web1:
    build: .
    ports:
      - 3000
    networks:
      webnetwork:

  web2:
    build: .
    ports:
      - 3000
    networks:
      webnetwork:

  web3:
    build: .
    ports:
      - 3000
    networks:
      webnetwork:

  load-balancer:
    build: nginx/
    ports:
      - 80:80
    volumes:
      # allows you to run docker commands from inside a container - https://medium.com/lucjuggery/about-var-run-docker-sock-3bfd276e12fd
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      webnetwork:

networks: 
  webnetwork: